services:
  wordpress:
    image: wordpress:latest
    container_name: ${PROJECT_NAME}_wordpress
    ports:
      - '${WORDPRESS_PORT}:80' # 各プロジェクトで異なるポート
    environment:
      WORDPRESS_DB_HOST: ${PROJECT_NAME}_db # データベースのホスト名
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - default_network

  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # 各プロジェクトで異なるボリューム名
    networks:
      - default_network

volumes:
  db_data:
    name: ${PROJECT_NAME}_db_data

networks:
  default_network:
    name: ${PROJECT_NAME}_network # 環境変数を使ってネットワーク名を動的に設定
    driver: bridge
